<?php
/**
 * (c) InPost UK Ltd <it_support@inpost.co.uk>
 * This source file is subject to the license that is bundled
 * with this source code in the file LICENSE.
 *
 * Built by NMedia Systems Ltd, <info@nmediasystems.com>
 */
?>

<?php if ($block->isInpost()): ?>
    <p><?php echo __('Once your order is ready to be collected, we\'ll also update you with text and email notification.') ?></p>
<?php endif; ?>
